version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: postgres_fast_api_5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: fast_api
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d fast_api" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  app:
    build: .
    container_name: fastapi_app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql+asyncpg://admin:admin@postgres:5432/fast_api
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  pgdata: